import React, { useState, useEffect } from 'react';
import { toast } from 'react-toastify';
import axios from 'axios';

function AddRecipeModal({ show, onClose, onAddRecipe, editRecipe }) {
  const emptyFormState = {
    name: "",
    category: "Veg",
    image: "",
    ingredients: "",
    instructions: "",
    time: "",
    servings: "",
    rating: Math.floor(Math.random() * 2) + 4,
    reviews: Math.floor(Math.random() * 50) + 5,
    difficulty: "Medium",
    author: "",
    description: "",
    calories: "",
    protein: "",
    carbs: "",
    fat: ""
  };

  const [newRecipe, setNewRecipe] = useState(emptyFormState);
  const [isAILoading, setIsAILoading] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // 🛠️ 1. New State to track if the current image is generated by AI
  const [isAIGenerated, setIsAIGenerated] = useState(false);

  useEffect(() => {
    if (editRecipe) {
      setNewRecipe({
        ...editRecipe,
        ingredients: editRecipe.ingredients ? editRecipe.ingredients.join(', ') : "",
        calories: editRecipe.nutrition?.calories || "",
        protein: editRecipe.nutrition?.protein || "",
        carbs: editRecipe.nutrition?.carbs || "",
        fat: editRecipe.nutrition?.fat || ""
      });
      setIsAIGenerated(false); // The AI ​​button will not be visible during editing.
    } else {
      setNewRecipe(emptyFormState);
      setIsAIGenerated(false);
    }
  }, [editRecipe, show]);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setNewRecipe({ ...newRecipe, [name]: value });

    // 🛠️ 2. If user manually types/pastes URL, hide AI button
    if (name === 'image') {
      setIsAIGenerated(false);
    }
  };

  // 🪄 Smart Logic: Gemini for Text + Smart Unsplash Search
  const handleMagicFill = async () => {
    if (!newRecipe.name.trim()) {
      toast.warning("Please enter a Recipe Name first! (e.g., Masala Dosa)");
      return;
    }

    setIsAILoading(true);
    setNewRecipe(prev => ({ ...prev, image: "" }));
    setIsAIGenerated(false);

    try {
      const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY;
      const UNSPLASH_ACCESS_KEY = import.meta.env.VITE_UNSPLASH_ACCESS_KEY;

      if (!GEMINI_API_KEY || !UNSPLASH_ACCESS_KEY) {
        toast.error("⚠️ Missing API Keys! Please check your .env file.");
        setIsAILoading(false);
        return;
      }

      toast.info("AI is cooking details & finding the best photo... 🪄📸");

      const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_API_KEY}`;
      const promptText = `
        I am building a recipe sharing application. Provide realistic recipe details for a dish named "${newRecipe.name}".
        Return ONLY a valid JSON object with the exact structure below. Do not include any markdown tags like \`\`\`json.
        {
          "category": "Choose EXACTLY ONE from this list: Veg, Non-Veg, Dessert, Italian, South Indian, Chinese, Fast Food",
          "description": "A catchy, delicious 2-line description of the dish",
          "time": "e.g., 30 mins",
          "servings": "e.g., 2 Servings",
          "difficulty": "Easy, Medium, or Hard",
          "ingredients": "Comma-separated list of 5-7 main ingredients",
          "instructions": "Brief step-by-step cooking instructions in 3 simple sentences.",
          "calories": "e.g. 350 kcal",
          "protein": "e.g. 15g",
          "carbs": "e.g. 45g",
          "fat": "e.g. 12g"
        }
      `;

      const geminiResponse = await fetch(geminiUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ contents: [{ parts: [{ text: promptText }] }] })
      });

      if (!geminiResponse.ok) {
        const errorData = await geminiResponse.json();
        throw new Error(`Gemini API Error: ${errorData.error?.message || 'Unknown'}`);
      }

      const geminiData = await geminiResponse.json();
      let geminiText = geminiData.candidates[0].content.parts[0].text;
      geminiText = geminiText.replace(/```json/g, "").replace(/```/g, "").trim();
      const aiData = JSON.parse(geminiText);

      let recipeImageUrl = "";
      let unsplashUrl = `https://api.unsplash.com/search/photos?query=${encodeURIComponent(newRecipe.name)}&client_id=${UNSPLASH_ACCESS_KEY}&per_page=30`;
      let unsplashResponse = await fetch(unsplashUrl);
      let unsplashData = await unsplashResponse.json();

      if (unsplashData.results && unsplashData.results.length > 0) {
        const randomIndex = Math.floor(Math.random() * unsplashData.results.length);
        recipeImageUrl = unsplashData.results[randomIndex].urls.regular;
      } else {
        let fallbackQuery = `${aiData.category} delicious food`;
        let fallbackUrl = `https://api.unsplash.com/search/photos?query=${encodeURIComponent(fallbackQuery)}&client_id=${UNSPLASH_ACCESS_KEY}&per_page=30`;
        let fallbackResponse = await fetch(fallbackUrl);
        let fallbackData = await fallbackResponse.json();

        if (fallbackData.results && fallbackData.results.length > 0) {
          const randomIndex = Math.floor(Math.random() * fallbackData.results.length);
          recipeImageUrl = fallbackData.results[randomIndex].urls.regular;
        }
      }

      setNewRecipe(prev => ({
        ...prev,
        category: aiData.category ? aiData.category.split(',')[0].trim() : "Veg",
        description: aiData.description || "",
        time: aiData.time || "",
        servings: aiData.servings || "",
        difficulty: aiData.difficulty || "Medium",
        ingredients: aiData.ingredients || "",
        instructions: aiData.instructions || "",
        calories: aiData.calories || "",
        protein: aiData.protein || "",
        carbs: aiData.carbs || "",
        fat: aiData.fat || "",
        image: recipeImageUrl
      }));

      // 🛠️ 3. Set to true since image came from AI/Unsplash
      setIsAIGenerated(true);

      toast.success("✨ Magic Fill & Photo Ready!");
    } catch (error) {
      console.error("Combined AI Error:", error);
      toast.error("AI couldn't generate details. Try again.");
    } finally {
      setIsAILoading(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (isSubmitting) return;
    setIsSubmitting(true);

    const ingredientsArray = newRecipe.ingredients
      .split(',')
      .map(ing => ing.trim())
      .filter(ing => ing !== "");

    const storedUser = JSON.parse(sessionStorage.getItem('user'));

    const recipeToAdd = {
      ...newRecipe,
      ingredients: ingredientsArray,
      author: storedUser?.name || storedUser?.email?.split('@')[0] || "Chef",
      nutrition: {
        calories: newRecipe.calories || "N/A",
        protein: newRecipe.protein || "N/A",
        carbs: newRecipe.carbs || "N/A",
        fat: newRecipe.fat || "N/A"
      }
    };

    try {
      const url = editRecipe
        ? `http://localhost:8080/api/recipes/${editRecipe._id}`
        : 'http://localhost:8080/api/recipes/';

      const method = editRecipe ? 'put' : 'post';

      const response = await axios[method](url, recipeToAdd, {
        withCredentials: true
      });

      toast.success(response.data.message || "Recipe saved successfully! ✨");

      onClose();
      setTimeout(() => {
        window.location.reload();
      }, 1500);

    } catch (error) {
      console.error("Error saving recipe:", error.response?.data || error.message);
      toast.error(error.response?.data?.message || "Session expired or error occurred. Please login again.");
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!show) return null;

  return (
    <div className="modal show d-block" style={{ backgroundColor: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(4px)', zIndex: '1060' }}>
      <div className="modal-dialog modal-dialog-centered modal-lg">
        <div className="modal-content border-0 shadow-lg" style={{ borderRadius: '20px' }}>
          <div className="modal-header border-0 pb-0">
            <h4 className="fw-bold text-primary mb-0">
              {editRecipe ? "Edit Recipe" : "Create New Recipe"}
            </h4>
            <button className="btn-close" onClick={onClose}></button>
          </div>

          <div className="modal-body p-4" style={{ maxHeight: '75vh', overflowY: 'auto' }}>
            <form onSubmit={handleSubmit}>

              <div className="row mb-3">
                <div className="col-md-6">
                  <label className="form-label small fw-bold">Recipe Name</label>
                  <div className="d-flex gap-2">
                    <input type="text" name="name" className="form-control rounded-3" placeholder="e.g. Pizza, Pasta, Biryani" required value={newRecipe.name} onChange={handleInputChange} />
                    <button
                      type="button"
                      className="btn btn-warning btn-sm rounded-3 fw-bold shadow-sm d-flex align-items-center justify-content-center px-3"
                      onClick={handleMagicFill}
                      disabled={isAILoading}
                      style={{ minWidth: '100px' }}
                    >
                      {isAILoading ? <span className="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> : '🪄 AI Fill'}
                    </button>
                  </div>
                </div>
                <div className="col-md-6">
                  <label className="form-label small fw-bold">Category</label>
                  <select name="category" className="form-select rounded-3" value={newRecipe.category} onChange={handleInputChange}>
                    <option value="Veg">Veg</option>
                    <option value="Non-Veg">Non-Veg</option>
                    <option value="Italian">Italian</option>
                    <option value="South Indian">South Indian</option>
                    <option value="Chinese">Chinese</option>
                    <option value="Dessert">Dessert</option>
                    <option value="Fast Food">Fast Food</option>
                  </select>
                </div>
              </div>

              <div className="row mb-3">
                <div className="col-md-6">
                  <label className="form-label small fw-bold">Cook Time</label>
                  <input type="text" name="time" className="form-control rounded-3" placeholder="e.g. 25 mins" value={newRecipe.time} onChange={handleInputChange} />
                </div>
                <div className="col-md-6">
                  <label className="form-label small fw-bold">Servings</label>
                  <input type="text" name="servings" className="form-control rounded-3" placeholder="e.g. 2 Servings" value={newRecipe.servings} onChange={handleInputChange} />
                </div>
              </div>

              <div className="mb-3">
                <label className="form-label small fw-bold">Brief Description</label>
                <textarea name="description" className="form-control rounded-3" rows="2" placeholder="Describe your delicious recipe..." required value={newRecipe.description} onChange={handleInputChange}></textarea>
              </div>

              <div className="mb-3">
                <label className="form-label small fw-bold">Ingredients</label>
                <input type="text" name="ingredients" className="form-control rounded-3" placeholder="e.g. Rice, Spices" required value={newRecipe.ingredients} onChange={handleInputChange} />
              </div>

              <div className="mb-3">
                <label className="form-label small fw-bold">Instructions</label>
                <textarea name="instructions" className="form-control rounded-3" rows="3" placeholder="Step 1... Step 2..." required value={newRecipe.instructions} onChange={handleInputChange}></textarea>
              </div>

              <h5 className="fw-bold text-dark mt-4 mb-3 border-bottom pb-2">Nutritional Information</h5>
              <div className="row mb-3 g-2">
                <div className="col-3">
                  <label className="form-label small fw-semibold">Calories</label>
                  <input type="text" name="calories" className="form-control rounded-3 form-control-sm" placeholder="e.g. 350 kcal" value={newRecipe.calories} onChange={handleInputChange} />
                </div>
                <div className="col-3">
                  <label className="form-label small fw-semibold">Protein</label>
                  <input type="text" name="protein" className="form-control rounded-3 form-control-sm" placeholder="e.g. 15g" value={newRecipe.protein} onChange={handleInputChange} />
                </div>
                <div className="col-3">
                  <label className="form-label small fw-semibold">Carbs</label>
                  <input type="text" name="carbs" className="form-control rounded-3 form-control-sm" placeholder="e.g. 45g" value={newRecipe.carbs} onChange={handleInputChange} />
                </div>
                <div className="col-3">
                  <label className="form-label small fw-semibold">Fat</label>
                  <input type="text" name="fat" className="form-control rounded-3 form-control-sm" placeholder="e.g. 12g" value={newRecipe.fat} onChange={handleInputChange} />
                </div>
              </div>

              {/* 🖼️ Image Options Section */}
              <div className="mb-4 p-3 rounded-3 border bg-light text-center">
                <label className="form-label d-block small fw-bold text-dark mb-3">
                  Recipe Image Options (Choose or Change)
                </label>

                {/* Image Preview Box */}
                {newRecipe.image ? (
                  <div className="position-relative mb-3">
                    <img
                      src={newRecipe.image}
                      alt="Food Preview"
                      className="rounded-3 shadow-sm img-thumbnail"
                      style={{ maxHeight: '220px', width: '100%', objectFit: 'cover' }}
                    />

                    {/* 🔄 Try Another Photo: Shows ONLY when image is generated via AI */}
                    {isAIGenerated && (
                      <button
                        type="button"
                        className="btn btn-sm btn-dark position-absolute top-0 end-0 m-2 rounded-pill px-3 shadow-sm fw-bold"
                        onClick={handleMagicFill}
                        title="Fetch another photo from AI/Unsplash"
                      >
                        🔄 Try Another Photo
                      </button>
                    )}
                  </div>
                ) : isAILoading ? (
                  <div className="py-5 text-muted">
                    <div className="spinner-border text-warning mb-2" role="status"></div>
                    <div className="small fw-semibold">Searching Unsplash...</div>
                  </div>
                ) : (
                  <div className="py-4 text-muted bg-white rounded-3 border border-dashed mb-3">
                    <span className="display-4 opacity-25">🖼️</span>
                    <div className="small mt-2 fw-semibold">Photo will appear here after AI Fill</div>
                  </div>
                )}

                {/* 🔗 Custom Image URL Input Box */}
                <div className="mb-3">
                  <input
                    type="url"
                    name="image"
                    className="form-control form-control-sm rounded-3"
                    placeholder="Paste direct image link here (e.g. from Google Images)"
                    value={newRecipe.image}
                    onChange={handleInputChange}
                  />
                  <div className="text-muted mt-1" style={{ fontSize: '10px' }}>
                    💡 Tip: Right-click any image on Google, select <b>"Copy Image Address"</b>, and paste it above to use your own custom photo!
                  </div>
                </div>

                {/* 📁 Local File Upload Option with Validation */}
                <div className="text-start">
                  <label className="form-label text-muted" style={{ fontSize: '11px' }}>
                    Or upload from your computer (JPG, PNG, WEBP, GIF, BMP):
                  </label>
                  <input
                    type="file"
                    accept="image/png, image/jpeg, image/jpg, image/webp, image/gif, image/bmp"
                    className="form-control form-control-sm rounded-3"
                    onChange={(e) => {
                      const file = e.target.files[0];
                      if (file) {
                        // 🛠️ Security check: Ensure the selected file is actually an image
                        if (!file.type.startsWith('image/')) {
                          toast.error("Please upload a valid image file (JPG, PNG, WEBP, GIF, BMP)!");
                          e.target.value = ""; // Clear the file input
                          return;
                        }

                        const reader = new FileReader();
                        reader.onloadend = () => {
                          setNewRecipe(prev => ({ ...prev, image: reader.result }));
                          setIsAIGenerated(false); // Hide AI button if uploaded from computer
                        };
                        reader.readAsDataURL(file);
                      }
                    }}
                  />
                </div>
              </div>

              <div className="text-end mt-4">
                <button type="button" className="btn btn-outline-secondary rounded-pill px-4 me-2" onClick={onClose}>Cancel</button>
                <button type="submit" className="btn btn-primary rounded-pill px-4 shadow-sm" disabled={isSubmitting}>
                  {isSubmitting ? "Saving..." : (editRecipe ? "Update Recipe" : "Add Recipe")}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}

export default AddRecipeModal;